############################################################
#
# web访问端口号 约定：8088
#
############################################################
server:
  port: 8089
tomcat:
  uri-encoding: UTF-8
  max-http-header-size: 80KB

############################################################
#
# 配置数据源信息
#
############################################################
spring:
  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动
    url: jdbc:mysql://124.222.149.140:3306/Applet?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=CST&testOnBorrow=true&validationQuery=select 1
    username: root
    password: GYhb888!
  hikari:
    connection-timeout: 30000 # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQ
    minimum-idle: 5 # 最小连接数
    maximum-pool-size: 20 # 最大连接数
    auto-commit: true # 自动提交
    idle-timeout: 600000 # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
    pool-name: DateSourceHikariCP # 连接池名字
    max-lifetime: 1800000 # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟
#    connection-test-query:select 1       mysql 的配置，时测试连接的
    connection-test-query: SELECT 1 from dual
  redis:
    database: 0
    host: 124.222.149.140
    port: 6379
    password: GYhb888!
#设置默认文件上传大小最大允许为20MB（系统默认为1MB，超出报错）
  servlet:
    multipart:
      max-file-size: 20MB


############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  type-aliases-package: com.gyhb.entity # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml # mapper映射文件
  configuration:
    jdbc-type-for-null: 'null' #注意：单引号

#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

############################################################
#
# mybatis mapper 配置
#
############################################################
 #通用 Mapper 配置
mapper:
  mappers: com.gyhb.my.mapper.MyMapper
  not-empty: false
#  identity: ORACLE
  identity: MYSQL
# 分页插件配置
pagehelper:
  helperDialect: mysql
#  helperDialect:oracle
  supportMethodsArguments: true

  ############################################################
  #
  # 腾讯云COS配置
  #
  ############################################################

qcloud:
  cos:
    bucket-name: xiangyin-1309666979
    bucket-region: ap-chengdu
    secret-key: oMddLmwpQmqd9PTGm10h7F7h01qOYR3P
    secret-id: AKIDPdcKlvoRouiHYYHkvpSnsgDTTBdnhKgl
